In [82]:
import polars as pl
import pandas as pd
from unidecode import unidecode

In [83]:
goodreads_book_df = pl.read_csv('datalake/clean/cleaned_books_data.csv').rename({
    'isbn13':'id', 'isbn':'ISBN_10','crawl_source':'crawl_source_url'
})

# Clean the string
goodreads_book_df = goodreads_book_df.with_columns(
    [
        pl.col(col).str.strip_chars("'").str.strip_chars('"').alias(col)
        for col in goodreads_book_df.columns if goodreads_book_df.schema[col] == pl.Utf8
    ]
)

# Add source column
goodreads_book_df = goodreads_book_df.with_columns(
    pl.lit('goodreads').alias('crawl_source')
)

goodreads_book_df

shape: (78_681, 15)
┌────────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ ISBN_10    ┆ id           ┆ title        ┆ image_url    ┆ … ┆ crawl_source ┆ average_rat ┆ series      ┆ crawl_sourc │
│ ---        ┆ ---          ┆ ---          ┆ ---          ┆   ┆ _url         ┆ ing         ┆ ---         ┆ e           │
│ str        ┆ str          ┆ str          ┆ str          ┆   ┆ ---          ┆ ---         ┆ str         ┆ ---         │
│            ┆              ┆              ┆              ┆   ┆ str          ┆ f64         ┆             ┆ str         │
╞════════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1662528396 ┆ 978166252839 ┆ Cruel Winter ┆ https://imag ┆ … ┆ https://www. ┆ 3.71        ┆ Under The   ┆ goodreads   │
│            ┆ 2            ┆ with You     ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆ Mistletoe   ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆ Collection  ┆             │
│ 0664266703 ┆ 978066426670 ┆ The Purpose  ┆ https://imag ┆ … ┆ https://www. ┆ 4.13        ┆ null        ┆ goodreads   │
│            ┆ 7            ┆ Gap:         ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Empowering   ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│            ┆              ┆ Co…          ┆              ┆   ┆              ┆             ┆             ┆             │
│ 166252823X ┆ 978166252823 ┆ All by My    ┆ https://imag ┆ … ┆ https://www. ┆ 2.61        ┆ Under The   ┆ goodreads   │
│            ┆ 1            ┆ Elf          ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆ Mistletoe   ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆ Collection  ┆             │
│ 1400341124 ┆ 978140034112 ┆ Mostly What  ┆ https://imag ┆ … ┆ https://www. ┆ 4.34        ┆ null        ┆ goodreads   │
│            ┆ 2            ┆ God Does:    ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Reflecti…    ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 1662529376 ┆ 978166252937 ┆ Only Santas  ┆ https://imag ┆ … ┆ https://www. ┆ 3.39        ┆ Under The   ┆ goodreads   │
│            ┆ 5            ┆ in the       ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆ Mistletoe   ┆             │
│            ┆              ┆ Building     ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆ Collection  ┆             │
│ …          ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ 1580625339 ┆ 978158062533 ┆ Everything   ┆ https://imag ┆ … ┆ https://www. ┆ 3.5         ┆ null        ┆ goodreads   │
│            ┆ 3            ┆ Ghost Book   ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 0879517107 ┆ 978087951710 ┆ Everything   ┆ https://imag ┆ … ┆ https://www. ┆ 3.88        ┆ null        ┆ goodreads   │
│            ┆ 6            ┆ and More     ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 158062684X ┆ 978158062684 ┆ The          ┆ https://imag ┆ … ┆ https://www. ┆ 4.0         ┆ null        ┆ goodreads   │
│            ┆ 2            ┆ Everything   ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Kids' Nature ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│            ┆              ┆ Bo…          ┆              ┆   ┆              ┆             ┆             ┆             │
│ 0226100316 ┆ 978022610031 ┆ Improvising  ┆ https://imag ┆ … ┆ https://www. ┆ 4.0         ┆ null        ┆ goodreads   │
│            ┆ 9            ┆ Theory:      ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Process an…  ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 0140512691 ┆ 978014051269 ┆ The Penguin  ┆ https://imag ┆ … ┆ https://www. ┆ 4.0         ┆ null        ┆ goodreads   │
│            ┆ 4            ┆ Dictionary   ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ of 19th…     ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
└────────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [84]:
# Further cleaning
# Change publish date to string date
goodreads_book_df = goodreads_book_df.with_columns(
    pl.col("publish_date")
    .cast(pl.Datetime("ms")) # Convert to Datetime
    .dt.strftime("%Y-%m-%d") # Format as "yyyy-mm-dd"
)

goodreads_book_df = goodreads_book_df.filter(pl.col("id") != "None")

In [85]:
print(goodreads_book_df.describe())
goodreads_book_df

shape: (9, 16)
┌────────────┬─────────┬───────────────┬───────────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ statistic  ┆ ISBN_10 ┆ id            ┆ title         ┆ … ┆ crawl_source ┆ average_rati ┆ series       ┆ crawl_source │
│ ---        ┆ ---     ┆ ---           ┆ ---           ┆   ┆ _url         ┆ ng           ┆ ---          ┆ ---          │
│ str        ┆ str     ┆ str           ┆ str           ┆   ┆ ---          ┆ ---          ┆ str          ┆ str          │
│            ┆         ┆               ┆               ┆   ┆ str          ┆ f64          ┆              ┆              │
╞════════════╪═════════╪═══════════════╪═══════════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ count      ┆ 77963   ┆ 77963         ┆ 77963         ┆ … ┆ 77963        ┆ 77963.0      ┆ 10415        ┆ 77963        │
│ null_count ┆ 0       ┆ 0             ┆ 0             ┆ … ┆ 0            ┆ 0.0          ┆ 67548        ┆ 0            │
│ mean       ┆ null    ┆ null          ┆ null          ┆ … ┆ null         ┆ 3.423754     ┆ null         ┆ null         │
│ std        ┆ null    ┆ null          ┆ null          ┆ … ┆ null         ┆ 1.350187     ┆ null         ┆ null         │
│ min        ┆ 983292  ┆ 20049070222   ┆ #1 Country    ┆ … ┆ https://www. ┆ 0.0          ┆ 100 Bullets, ┆ goodreads    │
│            ┆         ┆               ┆ Songs Of The  ┆   ┆ goodreads.co ┆              ┆ Vol. 1       ┆              │
│            ┆         ┆               ┆ 80's.         ┆   ┆ m/book…      ┆              ┆ #1-100 (19…  ┆              │
│ 25%        ┆ null    ┆ null          ┆ null          ┆ … ┆ null         ┆ 3.5          ┆ null         ┆ null         │
│ 50%        ┆ null    ┆ null          ┆ null          ┆ … ┆ null         ┆ 3.87         ┆ null         ┆ null         │
│ 75%        ┆ null    ┆ null          ┆ null          ┆ … ┆ null         ┆ 4.13         ┆ null         ┆ null         │
│ max        ┆ None    ┆ 9798991987400 ┆ 해리포터와    ┆ … ┆ https://www. ┆ 5.0          ┆ 魔法騎士レイ ┆ goodreads    │
│            ┆         ┆               ┆ 혼혈왕자 2    ┆   ┆ goodreads.co ┆              ┆ アース Magic ┆              │
│            ┆         ┆               ┆               ┆   ┆ m/book…      ┆              ┆ Knight       ┆              │
│            ┆         ┆               ┆               ┆   ┆              ┆              ┆ Rayeart…     ┆              │
└────────────┴─────────┴───────────────┴───────────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

shape: (77_963, 15)
┌────────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ ISBN_10    ┆ id           ┆ title        ┆ image_url    ┆ … ┆ crawl_source ┆ average_rat ┆ series      ┆ crawl_sourc │
│ ---        ┆ ---          ┆ ---          ┆ ---          ┆   ┆ _url         ┆ ing         ┆ ---         ┆ e           │
│ str        ┆ str          ┆ str          ┆ str          ┆   ┆ ---          ┆ ---         ┆ str         ┆ ---         │
│            ┆              ┆              ┆              ┆   ┆ str          ┆ f64         ┆             ┆ str         │
╞════════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1662528396 ┆ 978166252839 ┆ Cruel Winter ┆ https://imag ┆ … ┆ https://www. ┆ 3.71        ┆ Under The   ┆ goodreads   │
│            ┆ 2            ┆ with You     ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆ Mistletoe   ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆ Collection  ┆             │
│ 0664266703 ┆ 978066426670 ┆ The Purpose  ┆ https://imag ┆ … ┆ https://www. ┆ 4.13        ┆ null        ┆ goodreads   │
│            ┆ 7            ┆ Gap:         ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Empowering   ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│            ┆              ┆ Co…          ┆              ┆   ┆              ┆             ┆             ┆             │
│ 166252823X ┆ 978166252823 ┆ All by My    ┆ https://imag ┆ … ┆ https://www. ┆ 2.61        ┆ Under The   ┆ goodreads   │
│            ┆ 1            ┆ Elf          ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆ Mistletoe   ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆ Collection  ┆             │
│ 1400341124 ┆ 978140034112 ┆ Mostly What  ┆ https://imag ┆ … ┆ https://www. ┆ 4.34        ┆ null        ┆ goodreads   │
│            ┆ 2            ┆ God Does:    ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Reflecti…    ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 1662529376 ┆ 978166252937 ┆ Only Santas  ┆ https://imag ┆ … ┆ https://www. ┆ 3.39        ┆ Under The   ┆ goodreads   │
│            ┆ 5            ┆ in the       ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆ Mistletoe   ┆             │
│            ┆              ┆ Building     ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆ Collection  ┆             │
│ …          ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ 1580625339 ┆ 978158062533 ┆ Everything   ┆ https://imag ┆ … ┆ https://www. ┆ 3.5         ┆ null        ┆ goodreads   │
│            ┆ 3            ┆ Ghost Book   ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 0879517107 ┆ 978087951710 ┆ Everything   ┆ https://imag ┆ … ┆ https://www. ┆ 3.88        ┆ null        ┆ goodreads   │
│            ┆ 6            ┆ and More     ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆              ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 158062684X ┆ 978158062684 ┆ The          ┆ https://imag ┆ … ┆ https://www. ┆ 4.0         ┆ null        ┆ goodreads   │
│            ┆ 2            ┆ Everything   ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Kids' Nature ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│            ┆              ┆ Bo…          ┆              ┆   ┆              ┆             ┆             ┆             │
│ 0226100316 ┆ 978022610031 ┆ Improvising  ┆ https://imag ┆ … ┆ https://www. ┆ 4.0         ┆ null        ┆ goodreads   │
│            ┆ 9            ┆ Theory:      ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ Process an…  ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
│ 0140512691 ┆ 978014051269 ┆ The Penguin  ┆ https://imag ┆ … ┆ https://www. ┆ 4.0         ┆ null        ┆ goodreads   │
│            ┆ 4            ┆ Dictionary   ┆ es-na.ssl-im ┆   ┆ goodreads.co ┆             ┆             ┆             │
│            ┆              ┆ of 19th…     ┆ ages-a…      ┆   ┆ m/book…      ┆             ┆             ┆             │
└────────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [87]:
hardcover_book_df = pl.read_csv('datalake/hardcover/hardcover_books.csv', schema={
    "id": pl.String,
    "ISBN_10": pl.String,
    "title": pl.String,
    "description": pl.String,
    "image_url": pl.String,
    "author": pl.String,
    "language": pl.String,
    "publish_date": pl.String,
    "num_pages": pl.Int64,
    "crawl_source": pl.String,
    "hardcover_book_id": pl.Int64
})
print(hardcover_book_df.describe())
hardcover_book_df

shape: (9, 12)
┌────────────┬───────────────┬────────────┬──────────────┬───┬──────────────┬────────────┬──────────────┬──────────────┐
│ statistic  ┆ id            ┆ ISBN_10    ┆ title        ┆ … ┆ publish_date ┆ num_pages  ┆ crawl_source ┆ hardcover_bo │
│ ---        ┆ ---           ┆ ---        ┆ ---          ┆   ┆ ---          ┆ ---        ┆ ---          ┆ ok_id        │
│ str        ┆ str           ┆ str        ┆ str          ┆   ┆ str          ┆ f64        ┆ str          ┆ ---          │
│            ┆               ┆            ┆              ┆   ┆              ┆            ┆              ┆ f64          │
╞════════════╪═══════════════╪════════════╪══════════════╪═══╪══════════════╪════════════╪══════════════╪══════════════╡
│ count      ┆ 223378        ┆ 198761     ┆ 223365       ┆ … ┆ 202630       ┆ 223378.0   ┆ 223378       ┆ 223378.0     │
│ null_count ┆ 0             ┆ 24617      ┆ 13           ┆ … ┆ 20748        ┆ 0.0        ┆ 0            ┆ 0.0          │
│ mean       ┆ null          ┆ null       ┆ null         ┆ … ┆ null         ┆ 206.224163 ┆ null         ┆ 1.0828e6     │
│ std        ┆ null          ┆ null       ┆ null         ┆ … ┆ null         ┆ 409.621161 ┆ null         ┆ 389698.50853 │
│            ┆               ┆            ┆              ┆   ┆              ┆            ┆              ┆ 5            │
│ min        ┆ 0-415-33024-6 ┆ 281573     ┆ Captain      ┆ … ┆ -0013-01-01  ┆ 0.0        ┆ hardcover    ┆ 9.0          │
│            ┆               ┆            ┆ Underpants   ┆   ┆              ┆            ┆              ┆              │
│            ┆               ┆            ┆ and the Bi…  ┆   ┆              ┆            ┆              ┆              │
│ 25%        ┆ null          ┆ null       ┆ null         ┆ … ┆ null         ┆ 0.0        ┆ null         ┆ 846043.0     │
│ 50%        ┆ null          ┆ null       ┆ null         ┆ … ┆ null         ┆ 191.0      ┆ null         ┆ 1.126264e6   │
│ 75%        ┆ null          ┆ null       ┆ null         ┆ … ┆ null         ┆ 320.0      ┆ null         ┆ 1.414088e6   │
│ max        ┆ 9990100000490 ┆ 9999990932 ┆ ＤＡＹＳ,    ┆ … ┆ 42020-08-04  ┆ 99998.0    ┆ hardcover    ┆ 1.633581e6   │
│            ┆               ┆            ┆ Vol. 35      ┆   ┆              ┆            ┆              ┆              │
└────────────┴───────────────┴────────────┴──────────────┴───┴──────────────┴────────────┴──────────────┴──────────────┘

shape: (223_378, 11)
┌──────────────┬────────────┬──────────────┬──────────────┬───┬──────────────┬───────────┬──────────────┬──────────────┐
│ id           ┆ ISBN_10    ┆ title        ┆ description  ┆ … ┆ publish_date ┆ num_pages ┆ crawl_source ┆ hardcover_bo │
│ ---          ┆ ---        ┆ ---          ┆ ---          ┆   ┆ ---          ┆ ---       ┆ ---          ┆ ok_id        │
│ str          ┆ str        ┆ str          ┆ str          ┆   ┆ str          ┆ i64       ┆ str          ┆ ---          │
│              ┆            ┆              ┆              ┆   ┆              ┆           ┆              ┆ i64          │
╞══════════════╪════════════╪══════════════╪══════════════╪═══╪══════════════╪═══════════╪══════════════╪══════════════╡
│ 978071346987 ┆ 0713469870 ┆ Pattern      ┆ null         ┆ … ┆ 1993-07-01   ┆ 184       ┆ hardcover    ┆ 1189157      │
│ 5            ┆            ┆ Drafting for ┆              ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆ Dressmaki…   ┆              ┆   ┆              ┆           ┆              ┆              │
│ 978177656353 ┆ 1776563530 ┆ Head Girl    ┆ 'The first   ┆ … ┆ 2020-01-01   ┆ 107       ┆ hardcover    ┆ 868944       │
│ 1            ┆            ┆              ┆ time I read  ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆              ┆ Freya’s…     ┆   ┆              ┆           ┆              ┆              │
│ 978081121883 ┆ 081121883X ┆ Everything   ┆ A            ┆ … ┆ 1999-04-01   ┆ 129       ┆ hardcover    ┆ 651199       │
│ 2            ┆            ┆ and Nothing  ┆ pocket-sized ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆              ┆ Pearls       ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆              ┆ edition …    ┆   ┆              ┆           ┆              ┆              │
│ 978045005459 ┆ 0450054594 ┆ Cat's        ┆ null         ┆ … ┆ 1981-01-01   ┆ 98        ┆ hardcover    ┆ 1474502      │
│ 4            ┆            ┆ Revenge:     ┆              ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆ More Than    ┆              ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆ 101 U…       ┆              ┆   ┆              ┆           ┆              ┆              │
│ 978160705197 ┆ 1607051974 ┆ Block Party  ┆ null         ┆ … ┆ 2011-05-01   ┆ 0         ┆ hardcover    ┆ 1189155      │
│ 8            ┆            ┆ - The Modern ┆              ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆ Quilt…       ┆              ┆   ┆              ┆           ┆              ┆              │
│ …            ┆ …          ┆ …            ┆ …            ┆ … ┆ …            ┆ …         ┆ …            ┆ …            │
│ 978083484208 ┆ 0834842084 ┆ Gurdjieff    ┆ null         ┆ … ┆ 2019-02-05   ┆ 0         ┆ hardcover    ┆ 1303747      │
│ 3            ┆            ┆ Reconsidered ┆              ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆ : The Li…    ┆              ┆   ┆              ┆           ┆              ┆              │
│ 978006128877 ┆ null       ┆ Celebrate    ┆ Children     ┆ … ┆ 2008-01-01   ┆ 46        ┆ hardcover    ┆ 6230         │
│ 7            ┆            ┆ Children's   ┆ read aloud   ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆ Day/book …   ┆ in various…  ┆   ┆              ┆           ┆              ┆              │
│ 978173281921 ┆ null       ┆ Age of       ┆ null         ┆ … ┆ 2018-11-16   ┆ 425       ┆ hardcover    ┆ 1424537      │
│ 4            ┆            ┆ Asango: Book ┆              ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆ II           ┆              ┆   ┆              ┆           ┆              ┆              │
│ 978178108910 ┆ 1781089108 ┆ The Angel of ┆ This is not  ┆ … ┆ 2020-06-23   ┆ 464       ┆ hardcover    ┆ 448672       │
│ 1            ┆            ┆ the Crows    ┆ the story    ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆              ┆ you thin…    ┆   ┆              ┆           ┆              ┆              │
│ 978059333502 ┆ 0593335023 ┆ The Road     ┆ Two exes     ┆ … ┆ 2021-01-01   ┆ 401       ┆ hardcover    ┆ 467729       │
│ 4            ┆            ┆ Trip         ┆ reach a new  ┆   ┆              ┆           ┆              ┆              │
│              ┆            ┆              ┆ level of …   ┆   ┆              ┆           ┆              ┆              │
└──────────────┴────────────┴──────────────┴──────────────┴───┴──────────────┴───────────┴──────────────┴──────────────┘

#### Merging:

In [88]:
columns_to_merge = [
    "id",
    "ISBN_10",
    "title",
    "description",
    "image_url",
    "author",
    "language",
    "publish_date",
    "num_pages",
    "crawl_source"
]

merged_books = pl.concat([
    goodreads_book_df.select(columns_to_merge),
    hardcover_book_df.select(columns_to_merge)   
], how="vertical_relaxed")
merged_books

shape: (301_341, 10)
┌───────────────┬────────────┬────────────────┬───────────────┬───┬──────────┬──────────────┬───────────┬──────────────┐
│ id            ┆ ISBN_10    ┆ title          ┆ description   ┆ … ┆ language ┆ publish_date ┆ num_pages ┆ crawl_source │
│ ---           ┆ ---        ┆ ---            ┆ ---           ┆   ┆ ---      ┆ ---          ┆ ---       ┆ ---          │
│ str           ┆ str        ┆ str            ┆ str           ┆   ┆ str      ┆ str          ┆ i64       ┆ str          │
╞═══════════════╪════════════╪════════════════╪═══════════════╪═══╪══════════╪══════════════╪═══════════╪══════════════╡
│ 9781662528392 ┆ 1662528396 ┆ Cruel Winter   ┆ For two       ┆ … ┆ English  ┆ 2024-11-12   ┆ 73        ┆ goodreads    │
│               ┆            ┆ with You       ┆ former        ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ childhood     ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ frien…        ┆   ┆          ┆              ┆           ┆              │
│ 9780664266707 ┆ 0664266703 ┆ The Purpose    ┆ In The        ┆ … ┆ English  ┆ 2021-03-16   ┆ 256       ┆ goodreads    │
│               ┆            ┆ Gap:           ┆ Purpose Gap,  ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Empowering Co… ┆ Patrick Re…   ┆   ┆          ┆              ┆           ┆              │
│ 9781662528231 ┆ 166252823X ┆ All by My Elf  ┆ Secret        ┆ … ┆ English  ┆ 2024-11-12   ┆ 55        ┆ goodreads    │
│               ┆            ┆                ┆ crushes,      ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ spicy         ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ Christma…     ┆   ┆          ┆              ┆           ┆              │
│ 9781400341122 ┆ 1400341124 ┆ Mostly What    ┆ Mostly what   ┆ … ┆ English  ┆ 2024-02-20   ┆ 302       ┆ goodreads    │
│               ┆            ┆ God Does:      ┆ God does is   ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Reflecti…      ┆ love y…       ┆   ┆          ┆              ┆           ┆              │
│ 9781662529375 ┆ 1662529376 ┆ Only Santas in ┆ It’s          ┆ … ┆ English  ┆ 2024-11-12   ┆ 65        ┆ goodreads    │
│               ┆            ┆ the Building   ┆ beginning to  ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ look a lot l… ┆   ┆          ┆              ┆           ┆              │
│ …             ┆ …          ┆ …              ┆ …             ┆ … ┆ …        ┆ …            ┆ …         ┆ …            │
│ 9780834842083 ┆ 0834842084 ┆ Gurdjieff      ┆ null          ┆ … ┆ null     ┆ 2019-02-05   ┆ 0         ┆ hardcover    │
│               ┆            ┆ Reconsidered:  ┆               ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ The Li…        ┆               ┆   ┆          ┆              ┆           ┆              │
│ 9780061288777 ┆ null       ┆ Celebrate      ┆ Children read ┆ … ┆ English  ┆ 2008-01-01   ┆ 46        ┆ hardcover    │
│               ┆            ┆ Children's     ┆ aloud in      ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆ Day/book …     ┆ various…      ┆   ┆          ┆              ┆           ┆              │
│ 9781732819214 ┆ null       ┆ Age of Asango: ┆ null          ┆ … ┆ English  ┆ 2018-11-16   ┆ 425       ┆ hardcover    │
│               ┆            ┆ Book II        ┆               ┆   ┆          ┆              ┆           ┆              │
│ 9781781089101 ┆ 1781089108 ┆ The Angel of   ┆ This is not   ┆ … ┆ English  ┆ 2020-06-23   ┆ 464       ┆ hardcover    │
│               ┆            ┆ the Crows      ┆ the story you ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ thin…         ┆   ┆          ┆              ┆           ┆              │
│ 9780593335024 ┆ 0593335023 ┆ The Road Trip  ┆ Two exes      ┆ … ┆ English  ┆ 2021-01-01   ┆ 401       ┆ hardcover    │
│               ┆            ┆                ┆ reach a new   ┆   ┆          ┆              ┆           ┆              │
│               ┆            ┆                ┆ level of …    ┆   ┆          ┆              ┆           ┆              │
└───────────────┴────────────┴────────────────┴───────────────┴───┴──────────┴──────────────┴───────────┴──────────────┘

In [89]:
merged_books.describe()

shape: (9, 11)
┌────────────┬───────────────┬─────────┬────────────────────┬───┬───────────┬──────────────┬────────────┬──────────────┐
│ statistic  ┆ id            ┆ ISBN_10 ┆ title              ┆ … ┆ language  ┆ publish_date ┆ num_pages  ┆ crawl_source │
│ ---        ┆ ---           ┆ ---     ┆ ---                ┆   ┆ ---       ┆ ---          ┆ ---        ┆ ---          │
│ str        ┆ str           ┆ str     ┆ str                ┆   ┆ str       ┆ str          ┆ f64        ┆ str          │
╞════════════╪═══════════════╪═════════╪════════════════════╪═══╪═══════════╪══════════════╪════════════╪══════════════╡
│ count      ┆ 301341        ┆ 276724  ┆ 301328             ┆ … ┆ 257216    ┆ 279932       ┆ 298622.0   ┆ 301341       │
│ null_count ┆ 0             ┆ 24617   ┆ 13                 ┆ … ┆ 44125     ┆ 21409        ┆ 2719.0     ┆ 0            │
│ mean       ┆ null          ┆ null    ┆ null               ┆ … ┆ null      ┆ null         ┆ 224.973562 ┆ null         │
│ std        ┆ null          ┆ null    ┆ null               ┆ … ┆ null      ┆ null         ┆ 801.278554 ┆ null         │
│ min        ┆ 0-415-33024-6 ┆ 281573  ┆ Captain Underpants ┆ … ┆ Afrikaans ┆ +65535-01-01 ┆ 0.0        ┆ goodreads    │
│            ┆               ┆         ┆ and the Bi…        ┆   ┆           ┆              ┆            ┆              │
│ 25%        ┆ null          ┆ null    ┆ null               ┆ … ┆ null      ┆ null         ┆ 32.0       ┆ null         │
│ 50%        ┆ null          ┆ null    ┆ null               ┆ … ┆ null      ┆ null         ┆ 208.0      ┆ null         │
│ 75%        ┆ null          ┆ null    ┆ null               ┆ … ┆ null      ┆ null         ┆ 324.0      ┆ null         │
│ max        ┆ 9990100000490 ┆ None    ┆ ＤＡＹＳ, Vol. 35  ┆ … ┆ Wakashan  ┆ 42020-08-04  ┆ 380720.0   ┆ hardcover    │
│            ┆               ┆         ┆                    ┆   ┆ languages ┆              ┆            ┆              │
└────────────┴───────────────┴─────────┴────────────────────┴───┴───────────┴──────────────┴────────────┴──────────────┘

In [90]:
merged_books.filter(pl.col("id").is_duplicated()).sort("id")

shape: (78_520, 10)
┌───────────────┬────────────┬──────────────────┬─────────────┬───┬──────────┬──────────────┬───────────┬──────────────┐
│ id            ┆ ISBN_10    ┆ title            ┆ description ┆ … ┆ language ┆ publish_date ┆ num_pages ┆ crawl_source │
│ ---           ┆ ---        ┆ ---              ┆ ---         ┆   ┆ ---      ┆ ---          ┆ ---       ┆ ---          │
│ str           ┆ str        ┆ str              ┆ str         ┆   ┆ str      ┆ str          ┆ i64       ┆ str          │
╞═══════════════╪════════════╪══════════════════╪═════════════╪═══╪══════════╪══════════════╪═══════════╪══════════════╡
│ 0000199263477 ┆ 0199263477 ┆ An Introduction  ┆ null        ┆ … ┆ null     ┆ 1982-06-01   ┆ 0         ┆ hardcover    │
│               ┆            ┆ to the Philoso…  ┆             ┆   ┆          ┆              ┆           ┆              │
│ 0000199263477 ┆ 0199263477 ┆ An Introduction  ┆ null        ┆ … ┆ null     ┆ 1982-06-01   ┆ 0         ┆ hardcover    │
│               ┆            ┆ to the Philoso…  ┆             ┆   ┆          ┆              ┆           ┆              │
│ 0009511176641 ┆ null       ┆ Tähtilinna       ┆ null        ┆ … ┆ English  ┆ 2001-01-01   ┆ 302       ┆ hardcover    │
│ 0009511176641 ┆ null       ┆ Tähtilinna       ┆ null        ┆ … ┆ English  ┆ 2001-01-01   ┆ 302       ┆ hardcover    │
│ 0009511176641 ┆ null       ┆ Tähtilinna       ┆ null        ┆ … ┆ English  ┆ 2001-01-01   ┆ 302       ┆ hardcover    │
│ …             ┆ …          ┆ …                ┆ …           ┆ … ┆ …        ┆ …            ┆ …         ┆ …            │
│ 9847016600173 ┆ null       ┆ অপেক্ষা            ┆ null        ┆ … ┆ English  ┆ 1970-12-01   ┆ 220       ┆ hardcover    │
│ 9847027700831 ┆ null       ┆ নাটকসমগ্র          ┆ null        ┆ … ┆ English  ┆ 2010-02-01   ┆ 575       ┆ hardcover    │
│ 9847027700831 ┆ null       ┆ নাটকসমগ্র          ┆ null        ┆ … ┆ English  ┆ 2010-02-01   ┆ 575       ┆ hardcover    │
│ 9879848815380 ┆ 984050293X ┆ তা হলে বৃষ্টিদিন তা  ┆ null        ┆ … ┆ English  ┆ 2008-02-01   ┆ 111       ┆ hardcover    │
│               ┆            ┆ হলে ১৪ জুল…       ┆             ┆   ┆          ┆              ┆           ┆              │
│ 9879848815380 ┆ 984050293X ┆ তা হলে বৃষ্টিদিন তা  ┆ null        ┆ … ┆ English  ┆ 2008-02-01   ┆ 111       ┆ hardcover    │
│               ┆            ┆ হলে ১৪ জুল…       ┆             ┆   ┆          ┆              ┆           ┆              │
└───────────────┴────────────┴──────────────────┴─────────────┴───┴──────────┴──────────────┴───────────┴──────────────┘

In [91]:
merged_books_deduplicated = (
    merged_books.sort(by=["id", pl.col("crawl_source") == "hardcover"], descending=True)  # Prioritize "hardcover"
    .group_by("id")
    .agg(
        pl.col("title").first(),                        # Keep the first "title"
        pl.col("crawl_source").first(),  # Keep the first "crawl_source"
        pl.col("ISBN_10").max().fill_null(     pl.col("ISBN_10").min()),  # Fill missing `rating` from `goodreads`
        pl.col("description").max().fill_null( pl.col("description").min()),
        pl.col("image_url").max().fill_null(   pl.col("image_url").min()),
        pl.col("author").max().fill_null(      pl.col("author").min()),
        pl.col("language").first(),
        pl.col("publish_date").max().fill_null(      pl.col("publish_date").min()),
        pl.col("num_pages").max().fill_nan(      pl.col("num_pages").min()),
    )
)

In [92]:
print(merged_books_deduplicated)
merged_books_deduplicated.describe()

shape: (259_154, 10)
┌───────────────┬────────────────┬──────────────┬────────────┬───┬───────────────┬──────────┬──────────────┬───────────┐
│ id            ┆ title          ┆ crawl_source ┆ ISBN_10    ┆ … ┆ author        ┆ language ┆ publish_date ┆ num_pages │
│ ---           ┆ ---            ┆ ---          ┆ ---        ┆   ┆ ---           ┆ ---      ┆ ---          ┆ ---       │
│ str           ┆ str            ┆ str          ┆ str        ┆   ┆ str           ┆ str      ┆ str          ┆ i64       │
╞═══════════════╪════════════════╪══════════════╪════════════╪═══╪═══════════════╪══════════╪══════════════╪═══════════╡
│ 9780835608015 ┆ Sophia:        ┆ goodreads    ┆ 0835608018 ┆ … ┆ Caitlín       ┆ English  ┆ 2001-05-01   ┆ 463       │
│               ┆ Goddess of     ┆              ┆            ┆   ┆ Matthews      ┆          ┆              ┆           │
│               ┆ Wisdom, Bri…   ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9781591430568 ┆ How Animals    ┆ goodreads    ┆ 1591430569 ┆ … ┆ William       ┆ English  ┆ 2005-08-23   ┆ 312       │
│               ┆ Talk: And      ┆              ┆            ┆   ┆ Joseph Long   ┆          ┆              ┆           │
│               ┆ Other Pl…      ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780884195986 ┆ The Heavens    ┆ goodreads    ┆ 0884195988 ┆ … ┆ Anna Rountree ┆ English  ┆ 1999-01-01   ┆ 192       │
│               ┆ Opened:        ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│               ┆ Revealing …    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780202011745 ┆ The Biology of ┆ hardcover    ┆ 0202011747 ┆ … ┆ Richard D.    ┆ English  ┆ 1987-01-01   ┆ 301       │
│               ┆ Moral Systems  ┆              ┆            ┆   ┆ Alexander     ┆          ┆              ┆           │
│ 9789004336261 ┆ The Babylonian ┆ hardcover    ┆ 9004336265 ┆ … ┆ Enrique       ┆ English  ┆ 2017-02-06   ┆ 543       │
│               ┆ Disputation    ┆              ┆            ┆   ┆ Jiménez       ┆          ┆              ┆           │
│               ┆ Poe…           ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ …             ┆ …              ┆ …            ┆ …          ┆ … ┆ …             ┆ …        ┆ …            ┆ …         │
│ 9781401277536 ┆ Batman and the ┆ hardcover    ┆ 1401277535 ┆ … ┆ Mike W. Barr  ┆ English  ┆ 2018-02-20   ┆ 0         │
│               ┆ Outsiders,     ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│               ┆ Volu…          ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9781584853398 ┆ Circle of Fire ┆ goodreads    ┆ 1584853395 ┆ … ┆ Evelyn        ┆ English  ┆ 2001-01-01   ┆ 150       │
│               ┆                ┆              ┆            ┆   ┆ Coleman       ┆          ┆              ┆           │
│ 9789004356696 ┆ The Origins of ┆ hardcover    ┆ 900435669X ┆ … ┆ Aviva         ┆ null     ┆ null         ┆ 298       │
│               ┆ International  ┆              ┆            ┆   ┆ Guttmann      ┆          ┆              ┆           │
│               ┆ C…             ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780879305529 ┆ Chasin' that   ┆ hardcover    ┆ 0879305525 ┆ … ┆ Gayle Wardlow ┆ English  ┆ 1998-01-01   ┆ 291       │
│               ┆ Devil Music    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9781841480220 ┆ The Seven Wise ┆ goodreads    ┆ 1841480223 ┆ … ┆ Wafa'         ┆ English  ┆ 2000-01-01   ┆ 96        │
│               ┆ Princesses: A  ┆              ┆            ┆   ┆ Tarnowska     ┆          ┆              ┆           │
│               ┆ M…             ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
└───────────────┴────────────────┴──────────────┴────────────┴───┴───────────────┴──────────┴──────────────┴───────────┘

shape: (9, 11)
┌────────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬─────────────┬────────────┐
│ statistic  ┆ id           ┆ title        ┆ crawl_source ┆ … ┆ author       ┆ language     ┆ publish_dat ┆ num_pages  │
│ ---        ┆ ---          ┆ ---          ┆ ---          ┆   ┆ ---          ┆ ---          ┆ e           ┆ ---        │
│ str        ┆ str          ┆ str          ┆ str          ┆   ┆ str          ┆ str          ┆ ---         ┆ f64        │
│            ┆              ┆              ┆              ┆   ┆              ┆              ┆ str         ┆            │
╞════════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪═════════════╪════════════╡
│ count      ┆ 259154       ┆ 259144       ┆ 259154       ┆ … ┆ 258054       ┆ 221719       ┆ 241104      ┆ 256452.0   │
│ null_count ┆ 0            ┆ 10           ┆ 0            ┆ … ┆ 1100         ┆ 37435        ┆ 18050       ┆ 2702.0     │
│ mean       ┆ null         ┆ null         ┆ null         ┆ … ┆ null         ┆ null         ┆ null        ┆ 226.960706 │
│ std        ┆ null         ┆ null         ┆ null         ┆ … ┆ null         ┆ null         ┆ null        ┆ 859.418979 │
│ min        ┆ 0-415-33024- ┆ Captain      ┆ goodreads    ┆ … ┆ 	Priya       ┆ Afrikaans    ┆ +65535-01-0 ┆ 0.0        │
│            ┆ 6            ┆ Underpants   ┆              ┆   ┆ Saralkar     ┆              ┆ 1           ┆            │
│            ┆              ┆ and the Bi…  ┆              ┆   ┆              ┆              ┆             ┆            │
│ 25%        ┆ null         ┆ null         ┆ null         ┆ … ┆ null         ┆ null         ┆ null        ┆ 36.0       │
│ 50%        ┆ null         ┆ null         ┆ null         ┆ … ┆ null         ┆ null         ┆ null        ┆ 208.0      │
│ 75%        ┆ null         ┆ null         ┆ null         ┆ … ┆ null         ┆ null         ┆ null        ┆ 325.0      │
│ max        ┆ 999010000049 ┆ ＤＡＹＳ,    ┆ hardcover    ┆ … ┆ ｉｒｕ       ┆ Wakashan     ┆ 42020-08-04 ┆ 380720.0   │
│            ┆ 0            ┆ Vol. 35      ┆              ┆   ┆              ┆ languages    ┆             ┆            │
└────────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴─────────────┴────────────┘

In [93]:
merged_books_deduplicated.filter(pl.col("id").is_null())

shape: (0, 10)
┌─────┬───────┬──────────────┬─────────┬───┬────────┬──────────┬──────────────┬───────────┐
│ id  ┆ title ┆ crawl_source ┆ ISBN_10 ┆ … ┆ author ┆ language ┆ publish_date ┆ num_pages │
│ --- ┆ ---   ┆ ---          ┆ ---     ┆   ┆ ---    ┆ ---      ┆ ---          ┆ ---       │
│ str ┆ str   ┆ str          ┆ str     ┆   ┆ str    ┆ str      ┆ str          ┆ i64       │
╞═════╪═══════╪══════════════╪═════════╪═══╪════════╪══════════╪══════════════╪═══════════╡
└─────┴───────┴──────────────┴─────────┴───┴────────┴──────────┴──────────────┴───────────┘

In [94]:
merged_books_deduplicated.write_csv('datalake/clean_merge/books.csv')

### 2. Genres

In [6]:
hardcover_genre_df = pl.read_csv('datalake/hardcover/hardcover_book_genre.csv', schema={
    "id": pl.String,
    "genre": pl.String,
})
hardcover_genre_df

shape: (285_813, 2)
┌───────────────┬──────────────────────┐
│ id            ┆ genre                │
│ ---           ┆ ---                  │
│ str           ┆ str                  │
╞═══════════════╪══════════════════════╡
│ 9781776563531 ┆ Young Adult          │
│ 9781776563531 ┆ Poetry               │
│ 9780811218832 ┆ Classics             │
│ 9780811218832 ┆ Literary Collections │
│ 9780450054594 ┆ Comics               │
│ …             ┆ …                    │
│ 9780307460455 ┆ Politics             │
│ 9781250366788 ┆ Young Adult          │
│ 9781250366788 ┆ LGBTQ                │
│ 9781250366788 ┆ Young Adult Fiction  │
│ 9781788166560 ┆ LGBTQ                │
└───────────────┴──────────────────────┘

In [12]:
goodreads_genre_df = pl.read_csv('datalake/clean/genres.csv').rename({"name":"genre"})
goodreads_genre_df

shape: (1_022, 2)
┌──────────┬────────────────────┐
│ genre_id ┆ genre              │
│ ---      ┆ ---                │
│ i64      ┆ str                │
╞══════════╪════════════════════╡
│ 1        ┆ 14th Century       │
│ 2        ┆ Southern           │
│ 3        ┆ Agriculture        │
│ 4        ┆ Australia          │
│ 5        ┆ Mormonism          │
│ …        ┆ …                  │
│ 1018     ┆ Basketball         │
│ 1019     ┆ Witches            │
│ 1020     ┆ Native American    │
│ 1021     ┆ African Literature │
│ 1022     ┆ Multiplication     │
└──────────┴────────────────────┘

In [29]:
merged_genres = pl.concat([
    goodreads_genre_df.select("genre"),
    hardcover_genre_df.select("genre")
], how="vertical_relaxed")

merged_genres = merged_genres.unique()
merged_genres

shape: (6_905, 1)
┌──────────────────────────────┐
│ genre                        │
│ ---                          │
│ str                          │
╞══════════════════════════════╡
│ Glück                        │
│ Cabala                       │
│ Asymmetric warfare           │
│ Children's stories, German   │
│ Justice                      │
│ …                            │
│ Artists' preparatory studies │
│ Mythology, Roman             │
│ Hindi language               │
│ Anger                        │
│  Dien Bien Phu               │
└──────────────────────────────┘

In [72]:
merged_genres_stripped = merged_genres.with_columns(
    merged_genres['genre']
    .str.split(",")
    .list.eval(pl.element().str.strip_chars())
    .alias('split_genres')
).explode('split_genres').select('split_genres').unique()
merged_genres_stripped

shape: (6_370, 1)
┌─────────────────────────────────┐
│ split_genres                    │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Amnesia                         │
│ Guyana                          │
│ Post Colonial                   │
│ Cincinnati (Ohio)               │
│ Camino de Santiago de Composte… │
│ …                               │
│ Stress management               │
│ 12th Century                    │
│ Qi (Chinese philosophy)         │
│ Presidents                      │
│ Human engineering               │
└─────────────────────────────────┘

In [104]:
merged_genres_cleaned = merged_genres_stripped.with_columns(
    pl.col('split_genres')
    .map_elements(unidecode, return_dtype=pl.String)  # Apply unidecode
    .str.to_lowercase()
    .str.replace_all(r"[&'()+\-./:\[\]?`]", "")
    .str.replace(" ", "-")
    .str.slice(0,15)
    .alias("tag_genres")
)
merged_genres_cleaned

shape: (6_370, 2)
┌─────────────────────────────────┬─────────────────┐
│ split_genres                    ┆ tag_genres      │
│ ---                             ┆ ---             │
│ str                             ┆ str             │
╞═════════════════════════════════╪═════════════════╡
│ Amnesia                         ┆ amnesia         │
│ Guyana                          ┆ guyana          │
│ Post Colonial                   ┆ post-colonial   │
│ Cincinnati (Ohio)               ┆ cincinnati-ohio │
│ Camino de Santiago de Composte… ┆ camino-de santi │
│ …                               ┆ …               │
│ Stress management               ┆ stress-manageme │
│ 12th Century                    ┆ 12th-century    │
│ Qi (Chinese philosophy)         ┆ qi-chinese phil │
│ Presidents                      ┆ presidents      │
│ Human engineering               ┆ human-engineeri │
└─────────────────────────────────┴─────────────────┘

In [105]:
unique_chars = set(''.join(merged_genres_cleaned['tag_genres']))
print("Unique Characters:")
print(sorted(unique_chars))

Unique Characters:
[' ', '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [5]:
unique_chars = (
    merged_genres_stripped
    .select(pl.col("tag_genres").str.concat(delimiter=""))  # Concatenate all strings
    .unique()  # Get unique characters
)

print(sorted(set(unique_chars.item())))

NameError: name 'merged_genres_stripped' is not defined

### 2. Users

In [119]:
hardcover_user_df = pl.read_csv('datalake/hardcover/hardcover_users.csv').rename({
    'name':'full_name', 'id':'userid_source'
})

# Add source column
hardcover_user_df = hardcover_user_df.with_columns(
    pl.lit('hardcover').alias('account_source')
)

hardcover_user_df

shape: (21_336, 5)
┌───────────────┬───────────────────┬─────────────────┬─────────────┬────────────────┐
│ userid_source ┆ full_name         ┆ username        ┆ books_count ┆ account_source │
│ ---           ┆ ---               ┆ ---             ┆ ---         ┆ ---            │
│ i64           ┆ str               ┆ str             ┆ i64         ┆ str            │
╞═══════════════╪═══════════════════╪═════════════════╪═════════════╪════════════════╡
│ 18783         ┆ Nitin Rughoonauth ┆ Nitin           ┆ 7951        ┆ hardcover      │
│ 22985         ┆ Court             ┆ Courtreader     ┆ 7474        ┆ hardcover      │
│ 19573         ┆ Martha            ┆ Martha          ┆ 6933        ┆ hardcover      │
│ 13481         ┆ Deb Nance         ┆ DebNance        ┆ 6773        ┆ hardcover      │
│ 13318         ┆ abi               ┆ booksgamesvinyl ┆ 5666        ┆ hardcover      │
│ …             ┆ …                 ┆ …               ┆ …           ┆ …              │
│ 16898         ┆ Yaiza             ┆ Yai002          ┆ 0           ┆ hardcover      │
│ 14087         ┆ Stacy             ┆ Tacy_0301       ┆ 0           ┆ hardcover      │
│ 2609          ┆ Thomas Bartensud  ┆ bartensud       ┆ 0           ┆ hardcover      │
│ 19784         ┆ null              ┆ null            ┆ 0           ┆ hardcover      │
│ 16559         ┆ Mauro             ┆ maurocamara     ┆ 0           ┆ hardcover      │
└───────────────┴───────────────────┴─────────────────┴─────────────┴────────────────┘

In [120]:
goodreads_user_df = pl.read_csv('datalake/clean/users.csv').rename({
    'name':'full_name','user_id':'userid_source'
})

goodreads_user_df = goodreads_user_df.with_columns(
    pl.lit('goodreads').alias('account_source')
)

goodreads_user_df

shape: (23_592, 8)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬────────────┬──────────────┬──────────────┐
│ userid_source ┆ full_name    ┆ profile_url  ┆ total_rating ┆ total_review ┆ avg_rating ┆ image_url    ┆ account_sour │
│ ---           ┆ ---          ┆ ---          ┆ s            ┆ s            ┆ ---        ┆ ---          ┆ ce           │
│ i64           ┆ str          ┆ str          ┆ ---          ┆ ---          ┆ f64        ┆ str          ┆ ---          │
│               ┆              ┆              ┆ i64          ┆ i64          ┆            ┆              ┆ str          │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪════════════╪══════════════╪══════════════╡
│ 19185877      ┆ acacia       ┆ https://www. ┆ 835          ┆ 59           ┆ 4.3        ┆ https://imag ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ es.gr-assets ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ .com/u…      ┆              │
│ 169105231     ┆ kelli        ┆ https://www. ┆ 384          ┆ 1            ┆ 3.6        ┆ https://imag ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ es.gr-assets ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ .com/u…      ┆              │
│ 38623456      ┆ steph        ┆ https://www. ┆ 365          ┆ 0            ┆ 3.33       ┆ https://s.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ assets…      ┆              │
│ 8829118       ┆ mindy        ┆ https://www. ┆ 59           ┆ 2            ┆ 3.69       ┆ null         ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆              ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆              ┆              │
│ 179297432     ┆ kourtney     ┆ https://www. ┆ 64           ┆ 11           ┆ 4.28       ┆ null         ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆              ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆              ┆              │
│ …             ┆ …            ┆ …            ┆ …            ┆ …            ┆ …          ┆ …            ┆ …            │
│ 502678        ┆ Gail         ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 31968163      ┆ The          ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆ Overflowing  ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆ Inkwell      ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 43122073      ┆ Linda        ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 87271128      ┆ Khava        ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ https://i.gr ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆ -assets.com/ ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆ images…      ┆              │
│ 129029151     ┆ Her Half     ┆ https://www. ┆ 0            ┆ 0            ┆ 0.0        ┆ null         ┆ goodreads    │
│               ┆              ┆ goodreads.co ┆              ┆              ┆            ┆              ┆              │
│               ┆              ┆ m/user…      ┆              ┆              ┆            ┆              ┆              │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴────────────┴──────────────┴──────────────┘

In [121]:
goodreads_user_deduplicated = (
    goodreads_user_df.sort(by=["userid_source", "total_ratings"], descending=True)
    .group_by("userid_source")
    .agg(
        pl.col("full_name").first(), 
        pl.col("account_source").first()
    )
)

In [126]:
hardcover_user_deduplicated = (
    hardcover_user_df.sort(by=["userid_source", "books_count"], descending=True)
    .group_by("userid_source")
    .agg(
        pl.col("full_name").first(), 
        pl.col("account_source").first()
    )
)

In [132]:
# Check duplicates
print(goodreads_user_deduplicated.filter(pl.col("userid_source").is_duplicated()).sort("userid_source"))
print(hardcover_user_deduplicated.filter(pl.col("userid_source").is_duplicated()).sort("userid_source"))

shape: (0, 3)
┌───────────────┬───────────┬────────────────┐
│ userid_source ┆ full_name ┆ account_source │
│ ---           ┆ ---       ┆ ---            │
│ i64           ┆ str       ┆ str            │
╞═══════════════╪═══════════╪════════════════╡
└───────────────┴───────────┴────────────────┘
shape: (0, 3)
┌───────────────┬───────────┬────────────────┐
│ userid_source ┆ full_name ┆ account_source │
│ ---           ┆ ---       ┆ ---            │
│ i64           ┆ str       ┆ str            │
╞═══════════════╪═══════════╪════════════════╡
└───────────────┴───────────┴────────────────┘

In [133]:
merged_users = pl.concat([
    goodreads_user_deduplicated.select(["full_name","account_source","userid_source"]),
    hardcover_user_deduplicated.select(["full_name","account_source","userid_source"])   
], how="vertical_relaxed").sort(by=["account_source","userid_source"])

In [207]:
# Add user id (our user id)
merged_users_with_id_cleaned = merged_users.drop_nulls().with_columns(
    pl.arange(1, merged_users.drop_nulls().height+1).alias("new_user_id")  # Generates sequential ids starting from 0
)

In [208]:
print(merged_users_with_id_cleaned)

shape: (40_314, 4)
┌─────────────┬────────────────┬───────────────┬─────────────┐
│ full_name   ┆ account_source ┆ userid_source ┆ new_user_id │
│ ---         ┆ ---            ┆ ---           ┆ ---         │
│ str         ┆ str            ┆ i64           ┆ i64         │
╞═════════════╪════════════════╪═══════════════╪═════════════╡
│ Douglas     ┆ goodreads      ┆ 26            ┆ 1           │
│ Courtney    ┆ goodreads      ┆ 284           ┆ 2           │
│ kaitlin     ┆ goodreads      ┆ 675           ┆ 3           │
│ Scott       ┆ goodreads      ┆ 713           ┆ 4           │
│ erin        ┆ goodreads      ┆ 819           ┆ 5           │
│ …           ┆ …              ┆ …             ┆ …           │
│ Lily Ostler ┆ hardcover      ┆ 23475         ┆ 40310       │
│ Keelin      ┆ hardcover      ┆ 23477         ┆ 40311       │
│ ubyhb       ┆ hardcover      ┆ 23478         ┆ 40312       │
│ Ainsley     ┆ hardcover      ┆ 23481         ┆ 40313       │
│ Jose        ┆ hardcover      ┆ 23482         ┆ 40314       │
└─────────────┴────────────────┴───────────────┴─────────────┘

In [209]:
merged_users_with_id_cleaned.write_csv('datalake/clean_merge/users.csv')

### 3. RATINGS

In [201]:
goodreads_rating_df = pl.read_csv('datalake/clean/cleaned_reviews_data.csv',schema={
    "isbn": pl.String,
    "isbn13": pl.String,
    "user_id": pl.Int64,
    "rating_score": pl.Float64,
}).rename({
    'user_id':'userid_source'
})

goodreads_rating_df = goodreads_rating_df.with_columns(
    pl.lit('goodreads').alias('account_source')
)

goodreads_rating_df

shape: (845_857, 5)
┌────────────┬───────────────┬───────────────┬──────────────┬────────────────┐
│ isbn       ┆ isbn13        ┆ userid_source ┆ rating_score ┆ account_source │
│ ---        ┆ ---           ┆ ---           ┆ ---          ┆ ---            │
│ str        ┆ str           ┆ i64           ┆ f64          ┆ str            │
╞════════════╪═══════════════╪═══════════════╪══════════════╪════════════════╡
│ 0345465296 ┆ 9780345465290 ┆ 1742824       ┆ 5.0          ┆ goodreads      │
│ 0345465296 ┆ 9780345465290 ┆ 9180313       ┆ 5.0          ┆ goodreads      │
│ 0345465296 ┆ 9780345465290 ┆ 36153170      ┆ 5.0          ┆ goodreads      │
│ 0345465296 ┆ 9780345465290 ┆ 22819383      ┆ 4.0          ┆ goodreads      │
│ 0345465296 ┆ 9780345465290 ┆ 8845508       ┆ 5.0          ┆ goodreads      │
│ …          ┆ …             ┆ …             ┆ …            ┆ …              │
│ 0399155341 ┆ 9780399155345 ┆ 125982174     ┆ 5.0          ┆ goodreads      │
│ 0439554934 ┆ 9780439554930 ┆ 125982174     ┆ 5.0          ┆ goodreads      │
│ 0316015849 ┆ 9780316015844 ┆ 125982174     ┆ 5.0          ┆ goodreads      │
│ 0062024035 ┆ 9780062024039 ┆ 125982174     ┆ 5.0          ┆ goodreads      │
│ 0439023483 ┆ 9780439023481 ┆ 125982174     ┆ 5.0          ┆ goodreads      │
└────────────┴───────────────┴───────────────┴──────────────┴────────────────┘

In [213]:
# Merge to get new id
goodreads_rating_df_good = goodreads_rating_df.join(
    merged_users_with_id_cleaned, on=["userid_source","account_source"], how="left"
).drop_nulls("new_user_id")

goodreads_rating_df_good

shape: (448_104, 7)
┌────────────┬───────────────┬───────────────┬──────────────┬────────────────┬────────────────────────┬─────────────┐
│ isbn       ┆ isbn13        ┆ userid_source ┆ rating_score ┆ account_source ┆ full_name              ┆ new_user_id │
│ ---        ┆ ---           ┆ ---           ┆ ---          ┆ ---            ┆ ---                    ┆ ---         │
│ str        ┆ str           ┆ i64           ┆ f64          ┆ str            ┆ str                    ┆ i64         │
╞════════════╪═══════════════╪═══════════════╪══════════════╪════════════════╪════════════════════════╪═════════════╡
│ 0345465296 ┆ 9780345465290 ┆ 1742824       ┆ 5.0          ┆ goodreads      ┆ Jason Koivu            ┆ 3145        │
│ 0345465296 ┆ 9780345465290 ┆ 22819383      ┆ 4.0          ┆ goodreads      ┆ Timothy Boyd           ┆ 11776       │
│ 0345465296 ┆ 9780345465290 ┆ 929238        ┆ 4.0          ┆ goodreads      ┆ H (no longer expecting ┆ 1809        │
│            ┆               ┆               ┆              ┆                ┆ notific…               ┆             │
│ 0345465296 ┆ 9780345465290 ┆ 57773209      ┆ 3.0          ┆ goodreads      ┆ Chris Seltzer          ┆ 15652       │
│ 0815602057 ┆ 9780815602057 ┆ 316102        ┆ 3.0          ┆ goodreads      ┆ Krista the Krazy       ┆ 863         │
│            ┆               ┆               ┆              ┆                ┆ Kataloguer             ┆             │
│ …          ┆ …             ┆ …             ┆ …            ┆ …              ┆ …                      ┆ …           │
│ 0399155341 ┆ 9780399155345 ┆ 125982174     ┆ 5.0          ┆ goodreads      ┆ lacey                  ┆ 19640       │
│ 0439554934 ┆ 9780439554930 ┆ 125982174     ┆ 5.0          ┆ goodreads      ┆ lacey                  ┆ 19640       │
│ 0316015849 ┆ 9780316015844 ┆ 125982174     ┆ 5.0          ┆ goodreads      ┆ lacey                  ┆ 19640       │
│ 0062024035 ┆ 9780062024039 ┆ 125982174     ┆ 5.0          ┆ goodreads      ┆ lacey                  ┆ 19640       │
│ 0439023483 ┆ 9780439023481 ┆ 125982174     ┆ 5.0          ┆ goodreads      ┆ lacey                  ┆ 19640       │
└────────────┴───────────────┴───────────────┴──────────────┴────────────────┴────────────────────────┴─────────────┘

In [214]:
goodreads_rating_df_good.filter(pl.col('full_name').is_null())

shape: (0, 7)
┌──────┬────────┬───────────────┬──────────────┬────────────────┬───────────┬─────────────┐
│ isbn ┆ isbn13 ┆ userid_source ┆ rating_score ┆ account_source ┆ full_name ┆ new_user_id │
│ ---  ┆ ---    ┆ ---           ┆ ---          ┆ ---            ┆ ---       ┆ ---         │
│ str  ┆ str    ┆ i64           ┆ f64          ┆ str            ┆ str       ┆ i64         │
╞══════╪════════╪═══════════════╪══════════════╪════════════════╪═══════════╪═════════════╡
└──────┴────────┴───────────────┴──────────────┴────────────────┴───────────┴─────────────┘

In [222]:
hardcover_rating_df = pl.read_csv('datalake/hardcover/hardcover_ratings.csv',schema={
    "rating": pl.Float64,
    "book_id": pl.Int64,
    "user_id": pl.Int64,
    "date_added": pl.String,
    "edition_id": pl.Int64
}).rename({
    'book_id': 'hardcover_book_id',
    'user_id':'userid_source',
    'rating':'rating_score'
})

hardcover_rating_df = hardcover_rating_df.with_columns(
    pl.lit('hardcover').alias('account_source')
)

print(hardcover_rating_df.describe())
hardcover_rating_df

shape: (9, 7)
┌────────────┬──────────────┬───────────────────┬───────────────┬────────────┬─────────────┬────────────────┐
│ statistic  ┆ rating_score ┆ hardcover_book_id ┆ userid_source ┆ date_added ┆ edition_id  ┆ account_source │
│ ---        ┆ ---          ┆ ---               ┆ ---           ┆ ---        ┆ ---         ┆ ---            │
│ str        ┆ f64          ┆ f64               ┆ f64           ┆ str        ┆ f64         ┆ str            │
╞════════════╪══════════════╪═══════════════════╪═══════════════╪════════════╪═════════════╪════════════════╡
│ count      ┆ 1.631332e6   ┆ 1.631332e6        ┆ 1.631332e6    ┆ 1631332    ┆ 1.628765e6  ┆ 1631332        │
│ null_count ┆ 0.0          ┆ 0.0               ┆ 0.0           ┆ 0          ┆ 2567.0      ┆ 0              │
│ mean       ┆ 3.854516     ┆ 543281.600496     ┆ 10790.778025  ┆ null       ┆ 2.4687e7    ┆ null           │
│ std        ┆ 0.96229      ┆ 378920.3298       ┆ 6541.648061   ┆ null       ┆ 9.4193e6    ┆ null           │
│ min        ┆ 0.5          ┆ 1.0               ┆ 1.0           ┆ 0007-07-17 ┆ 179.0       ┆ hardcover      │
│ 25%        ┆ 3.0          ┆ 326923.0          ┆ 5608.0        ┆ null       ┆ 1.9635348e7 ┆ null           │
│ 50%        ┆ 4.0          ┆ 440155.0          ┆ 10202.0       ┆ null       ┆ 3.0402254e7 ┆ null           │
│ 75%        ┆ 5.0          ┆ 661730.0          ┆ 15776.0       ┆ null       ┆ 3.0735275e7 ┆ null           │
│ max        ┆ 5.0          ┆ 1.630682e6        ┆ 23251.0       ┆ 2024-12-12 ┆ 3.1709679e7 ┆ hardcover      │
└────────────┴──────────────┴───────────────────┴───────────────┴────────────┴─────────────┴────────────────┘

shape: (1_631_332, 6)
┌──────────────┬───────────────────┬───────────────┬────────────┬────────────┬────────────────┐
│ rating_score ┆ hardcover_book_id ┆ userid_source ┆ date_added ┆ edition_id ┆ account_source │
│ ---          ┆ ---               ┆ ---           ┆ ---        ┆ ---        ┆ ---            │
│ f64          ┆ i64               ┆ i64           ┆ str        ┆ i64        ┆ str            │
╞══════════════╪═══════════════════╪═══════════════╪════════════╪════════════╪════════════════╡
│ 3.0          ┆ 1111086           ┆ 6359          ┆ 0007-07-17 ┆ 31135094   ┆ hardcover      │
│ 5.0          ┆ 265718            ┆ 20299         ┆ 0008-01-18 ┆ 3537983    ┆ hardcover      │
│ 4.0          ┆ 378793            ┆ 20299         ┆ 0008-02-14 ┆ 8631567    ┆ hardcover      │
│ 5.0          ┆ 427391            ┆ 20299         ┆ 0008-02-14 ┆ 30193579   ┆ hardcover      │
│ 4.0          ┆ 429541            ┆ 20299         ┆ 0008-02-14 ┆ 19508505   ┆ hardcover      │
│ …            ┆ …                 ┆ …             ┆ …          ┆ …          ┆ …              │
│ 3.0          ┆ 501689            ┆ 11761         ┆ 2021-04-19 ┆ 30451470   ┆ hardcover      │
│ 3.0          ┆ 437921            ┆ 10357         ┆ 2021-04-19 ┆ 31263374   ┆ hardcover      │
│ 5.0          ┆ 1238232           ┆ 10357         ┆ 2021-04-19 ┆ 31263253   ┆ hardcover      │
│ 5.0          ┆ 20941             ┆ 10292         ┆ 2021-04-19 ┆ 30399881   ┆ hardcover      │
│ 4.0          ┆ 441044            ┆ 2191          ┆ 2021-04-19 ┆ 30391967   ┆ hardcover      │
└──────────────┴───────────────────┴───────────────┴────────────┴────────────┴────────────────┘

In [223]:
# Merge to get new id
hardcover_rating_df_with_user = hardcover_rating_df.join(
    merged_users_with_id_cleaned, on=["userid_source","account_source"], how="left"
).drop_nulls("new_user_id")

hardcover_rating_df_with_user

shape: (1_608_340, 8)
┌──────────────┬──────────────────┬───────────────┬────────────┬────────────┬────────────────┬───────────┬─────────────┐
│ rating_score ┆ hardcover_book_i ┆ userid_source ┆ date_added ┆ edition_id ┆ account_source ┆ full_name ┆ new_user_id │
│ ---          ┆ d                ┆ ---           ┆ ---        ┆ ---        ┆ ---            ┆ ---       ┆ ---         │
│ f64          ┆ ---              ┆ i64           ┆ str        ┆ i64        ┆ str            ┆ str       ┆ i64         │
│              ┆ i64              ┆               ┆            ┆            ┆                ┆           ┆             │
╞══════════════╪══════════════════╪═══════════════╪════════════╪════════════╪════════════════╪═══════════╪═════════════╡
│ 3.0          ┆ 1111086          ┆ 6359          ┆ 0007-07-17 ┆ 31135094   ┆ hardcover      ┆ Shannon   ┆ 27922       │
│ 5.0          ┆ 265718           ┆ 20299         ┆ 0008-01-18 ┆ 3537983    ┆ hardcover      ┆ SSK       ┆ 38008       │
│ 4.0          ┆ 378793           ┆ 20299         ┆ 0008-02-14 ┆ 8631567    ┆ hardcover      ┆ SSK       ┆ 38008       │
│ 5.0          ┆ 427391           ┆ 20299         ┆ 0008-02-14 ┆ 30193579   ┆ hardcover      ┆ SSK       ┆ 38008       │
│ 4.0          ┆ 429541           ┆ 20299         ┆ 0008-02-14 ┆ 19508505   ┆ hardcover      ┆ SSK       ┆ 38008       │
│ …            ┆ …                ┆ …             ┆ …          ┆ …          ┆ …              ┆ …         ┆ …           │
│ 3.0          ┆ 501689           ┆ 11761         ┆ 2021-04-19 ┆ 30451470   ┆ hardcover      ┆ j         ┆ 31919       │
│ 3.0          ┆ 437921           ┆ 10357         ┆ 2021-04-19 ┆ 31263374   ┆ hardcover      ┆ Andrei    ┆ 30887       │
│ 5.0          ┆ 1238232          ┆ 10357         ┆ 2021-04-19 ┆ 31263253   ┆ hardcover      ┆ Andrei    ┆ 30887       │
│ 5.0          ┆ 20941            ┆ 10292         ┆ 2021-04-19 ┆ 30399881   ┆ hardcover      ┆ aya       ┆ 30831       │
│ 4.0          ┆ 441044           ┆ 2191          ┆ 2021-04-19 ┆ 30391967   ┆ hardcover      ┆ Andy      ┆ 24903       │
└──────────────┴──────────────────┴───────────────┴────────────┴────────────┴────────────────┴───────────┴─────────────┘

In [228]:
hardcover_rating_df_with_user.sort(by=["hardcover_book_id","new_user_id"])

shape: (1_608_340, 8)
┌──────────────┬─────────────────┬───────────────┬────────────┬────────────┬─────────────────┬───────────┬─────────────┐
│ rating_score ┆ hardcover_book_ ┆ userid_source ┆ date_added ┆ edition_id ┆ account_source  ┆ full_name ┆ new_user_id │
│ ---          ┆ id              ┆ ---           ┆ ---        ┆ ---        ┆ ---             ┆ ---       ┆ ---         │
│ f64          ┆ ---             ┆ i64           ┆ str        ┆ i64        ┆ str             ┆ str       ┆ i64         │
│              ┆ i64             ┆               ┆            ┆            ┆                 ┆           ┆             │
╞══════════════╪═════════════════╪═══════════════╪════════════╪════════════╪═════════════════╪═══════════╪═════════════╡
│ 3.0          ┆ 1               ┆ 641           ┆ 2021-01-21 ┆ 759160     ┆ hardcover       ┆ winters   ┆ 23874       │
│ 4.0          ┆ 1               ┆ 5870          ┆ 2014-04-25 ┆ 25224958   ┆ hardcover       ┆ Spriggana ┆ 27546       │
│ 5.0          ┆ 1               ┆ 7178          ┆ 2024-09-16 ┆ 25224958   ┆ hardcover       ┆ Esme      ┆ 28511       │
│ 3.0          ┆ 1               ┆ 10282         ┆ 2022-06-25 ┆ 25224958   ┆ hardcover       ┆ Anki      ┆ 30823       │
│ 4.0          ┆ 1               ┆ 12795         ┆ 2015-06-25 ┆ 759160     ┆ hardcover       ┆ Laura     ┆ 32671       │
│ …            ┆ …               ┆ …             ┆ …          ┆ …          ┆ …               ┆ …         ┆ …           │
│ 5.0          ┆ 1630673         ┆ 23250         ┆ 2014-03-13 ┆ 31709666   ┆ hardcover       ┆ Daria     ┆ 40145       │
│ 2.0          ┆ 1630675         ┆ 23250         ┆ 2024-04-26 ┆ 31709663   ┆ hardcover       ┆ Daria     ┆ 40145       │
│ 3.0          ┆ 1630676         ┆ 23250         ┆ 2024-04-26 ┆ 31709667   ┆ hardcover       ┆ Daria     ┆ 40145       │
│ 5.0          ┆ 1630681         ┆ 23250         ┆ 2013-11-06 ┆ 31709677   ┆ hardcover       ┆ Daria     ┆ 40145       │
│ 4.0          ┆ 1630682         ┆ 21622         ┆ 2024-12-12 ┆ 31709679   ┆ hardcover       ┆ Anna      ┆ 38957       │
│              ┆                 ┆               ┆            ┆            ┆                 ┆ Tschetter ┆             │
└──────────────┴─────────────────┴───────────────┴────────────┴────────────┴─────────────────┴───────────┴─────────────┘

In [232]:
# Get isbn
hardcover_rating_df_good = hardcover_rating_df_with_user.join(
    hardcover_book_df, on="hardcover_book_id", how="left"
    
).drop_nulls("id").select(
    ["rating_score", "new_user_id","account_source","id"]
).rename({'id':'isbn13'})

hardcover_rating_df_good

shape: (389_639, 18)
┌──────────────┬─────────────────┬───────────────┬────────────┬───┬──────────┬──────────────┬───────────┬──────────────┐
│ rating_score ┆ hardcover_book_ ┆ userid_source ┆ date_added ┆ … ┆ language ┆ publish_date ┆ num_pages ┆ crawl_source │
│ ---          ┆ id              ┆ ---           ┆ ---        ┆   ┆ ---      ┆ ---          ┆ ---       ┆ ---          │
│ f64          ┆ ---             ┆ i64           ┆ str        ┆   ┆ str      ┆ str          ┆ i64       ┆ str          │
│              ┆ i64             ┆               ┆            ┆   ┆          ┆              ┆           ┆              │
╞══════════════╪═════════════════╪═══════════════╪════════════╪═══╪══════════╪══════════════╪═══════════╪══════════════╡
│ 4.0          ┆ 189532          ┆ 20299         ┆ 0008-02-25 ┆ … ┆ English  ┆ 1987-01-01   ┆ 542       ┆ hardcover    │
│ 4.0          ┆ 189532          ┆ 20299         ┆ 0008-02-25 ┆ … ┆ English  ┆ 1987-01-01   ┆ 542       ┆ hardcover    │
│ 4.0          ┆ 189532          ┆ 20299         ┆ 0008-02-25 ┆ … ┆ English  ┆ 1987-01-01   ┆ 542       ┆ hardcover    │
│ 4.0          ┆ 331156          ┆ 20299         ┆ 0008-03-13 ┆ … ┆ English  ┆ 1937-01-01   ┆ 128       ┆ hardcover    │
│ 4.0          ┆ 331156          ┆ 20299         ┆ 0008-03-13 ┆ … ┆ English  ┆ 1937-01-01   ┆ 128       ┆ hardcover    │
│ …            ┆ …               ┆ …             ┆ …          ┆ … ┆ …        ┆ …            ┆ …         ┆ …            │
│ 2.0          ┆ 1474278         ┆ 17635         ┆ 2021-04-19 ┆ … ┆ English  ┆ 1978-08-01   ┆ 251       ┆ hardcover    │
│ 5.0          ┆ 432523          ┆ 17635         ┆ 2021-04-19 ┆ … ┆ English  ┆ 1951-01-01   ┆ 41        ┆ hardcover    │
│ 4.0          ┆ 259662          ┆ 2488          ┆ 2021-04-19 ┆ … ┆ English  ┆ 1980-01-01   ┆ 480       ┆ hardcover    │
│ 5.0          ┆ 1809            ┆ 16430         ┆ 2021-04-19 ┆ … ┆ English  ┆ 2011-10-19   ┆ 331       ┆ hardcover    │
│ 5.0          ┆ 20941           ┆ 10292         ┆ 2021-04-19 ┆ … ┆ English  ┆ 2019-09-10   ┆ 448       ┆ hardcover    │
└──────────────┴─────────────────┴───────────────┴────────────┴───┴──────────┴──────────────┴───────────┴──────────────┘

In [225]:
columns_to_get = ["rating_score","new_user_id","isbn13","account_source"]

merged_rating = pl.concat([
    goodreads_rating_df_good.select(columns_to_get),
    hardcover_rating_df_good.select(columns_to_get)   
], how="vertical_relaxed")

In [226]:
merged_rating

shape: (837_743, 4)
┌──────────────┬─────────────┬───────────────┬────────────────┐
│ rating_score ┆ new_user_id ┆ isbn13        ┆ account_source │
│ ---          ┆ ---         ┆ ---           ┆ ---            │
│ f64          ┆ i64         ┆ str           ┆ str            │
╞══════════════╪═════════════╪═══════════════╪════════════════╡
│ 5.0          ┆ 3145        ┆ 9780345465290 ┆ goodreads      │
│ 4.0          ┆ 11776       ┆ 9780345465290 ┆ goodreads      │
│ 4.0          ┆ 1809        ┆ 9780345465290 ┆ goodreads      │
│ 3.0          ┆ 15652       ┆ 9780345465290 ┆ goodreads      │
│ 3.0          ┆ 863         ┆ 9780815602057 ┆ goodreads      │
│ …            ┆ …           ┆ …             ┆ …              │
│ 2.0          ┆ 36071       ┆ 9780722158753 ┆ hardcover      │
│ 5.0          ┆ 36071       ┆ 9780789156327 ┆ hardcover      │
│ 4.0          ┆ 25138       ┆ 9780770430078 ┆ hardcover      │
│ 5.0          ┆ 35217       ┆ 9781489054982 ┆ hardcover      │
│ 5.0          ┆ 30831       ┆ 9781250313195 ┆ hardcover      │
└──────────────┴─────────────┴───────────────┴────────────────┘

In [220]:
merged_rating.write_csv('datalake/clean_merge/ratings.csv')