In [94]:
# Libraries for data preparation & visualization
import numpy as np
import polars as pl
import pandas as pd

In [96]:
# Use your path in local
book   = pl.read_csv("./datalake/clean_merge/books.csv", schema={
    'isbn13': pl.String,
    'title': pl.String,
    'crawl_source': pl.String,
    'isbn10': pl.String,
    'description': pl.String,
    'image_url': pl.String,
    'author': pl.String,
    'language': pl.String,
    'publish_date': pl.String,
    'num_pages': pl.Int64
}, new_columns=[
    'isbn13','title','crawl_source','isbn10'
])

book_genre = pl.read_csv('./datalake/clean_merge/book_genres.csv', schema={
    'isbn13': pl.String,
    'genre_name': pl.String,
})

In [97]:
print(book)
print(book_genre)

shape: (284_893, 10)
┌───────────────┬────────────────┬──────────────┬────────────┬───┬───────────────┬──────────┬──────────────┬───────────┐
│ isbn13        ┆ title          ┆ crawl_source ┆ isbn10     ┆ … ┆ author        ┆ language ┆ publish_date ┆ num_pages │
│ ---           ┆ ---            ┆ ---          ┆ ---        ┆   ┆ ---           ┆ ---      ┆ ---          ┆ ---       │
│ str           ┆ str            ┆ str          ┆ str        ┆   ┆ str           ┆ str      ┆ str          ┆ i64       │
╞═══════════════╪════════════════╪══════════════╪════════════╪═══╪═══════════════╪══════════╪══════════════╪═══════════╡
│ 9783946642879 ┆ Hattest du     ┆ goodreads    ┆ 394664287X ┆ … ┆ Peer          ┆ German   ┆ 2020-04-01   ┆ 36        │
│               ┆ eigentlich     ┆              ┆            ┆   ┆ Jongeling     ┆          ┆              ┆           │
│               ┆ schon di…      ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9782368529539 ┆ My Home Hero - ┆ hardcover    ┆ 2368529535 ┆ … ┆ Masashi Asaki ┆ null     ┆ null         ┆ 0         │
│               ┆ tome 10        ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780590439671 ┆ The Story Of   ┆ hardcover    ┆ 0590439677 ┆ … ┆ Robert Coles  ┆ English  ┆ 1993-01-01   ┆ 32        │
│               ┆ Ruby Bridges   ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780063216051 ┆ The Do-Over    ┆ hardcover    ┆ null       ┆ … ┆ Suzanne Park  ┆ English  ┆ 2023-01-01   ┆ 368       │
│ 9798329760972 ┆ Wyvern's Gold  ┆ hardcover    ┆ 1956455752 ┆ … ┆ A.H. Hadley   ┆ null     ┆ 2024-07-26   ┆ 572       │
│ …             ┆ …              ┆ …            ┆ …          ┆ … ┆ …             ┆ …        ┆ …            ┆ …         │
│ 9781683228615 ┆ Worry Less,    ┆ hardcover    ┆ 1683228618 ┆ … ┆ Donna K.      ┆ null     ┆ null         ┆ 0         │
│               ┆ Pray More: A   ┆              ┆            ┆   ┆ Maltese       ┆          ┆              ┆           │
│               ┆ Woman…         ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9781250238016 ┆ The            ┆ hardcover    ┆ 1250238013 ┆ … ┆ Robert W. Bly ┆ English  ┆ 1985-01-01   ┆ 432       │
│               ┆ Copywriter's   ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│               ┆ Handbook       ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9798322657149 ┆ The Pact       ┆ goodreads    ┆ None       ┆ … ┆ Helena Sage   ┆ English  ┆ 2024-05-02   ┆ 501       │
│ 9780804747547 ┆ Yangtze        ┆ goodreads    ┆ 0804747547 ┆ … ┆ Linda Butler  ┆ English  ┆ 2004-10-12   ┆ 204       │
│               ┆ Remembered:    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│               ┆ The River …    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780965047623 ┆ The Very       ┆ hardcover    ┆ 0965047628 ┆ … ┆ George        ┆ null     ┆ 2000-11-24   ┆ 84        │
│               ┆ Persistent     ┆              ┆            ┆   ┆ Saunders      ┆          ┆              ┆           │
│               ┆ Gappers of…    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
└───────────────┴────────────────┴──────────────┴────────────┴───┴───────────────┴──────────┴──────────────┴───────────┘
shape: (682_222, 2)
┌───────────────┬─────────────────┐
│ isbn13        ┆ genre_name      │
│ ---           ┆ ---             │
│ str           ┆ str             │
╞═══════════════╪═════════════════╡
│ 9780761823889 ┆ Anthropology    │
│ 9782897771034 ┆ Fiction         │
│ 9789021439587 ┆ Authors         │
│ 9780553274813 ┆ Humor           │
│ 9781619638617 ┆ Science Fiction │
│ …             ┆ …               │
│ 9780060512149 ┆ Fiction         │
│ 9780892552900 ┆ College         │
│ 9780446571746 ┆ Science fiction │
│ 9781591797944 ┆ Mind & Spirit   │
│ 9781910931547 ┆ Comedy          │
└───────────────┴─────────────────┘

In [98]:
book_genre_joined = (
    book_genre
    .group_by("isbn13")
    .agg(
        pl.col("genre_name").str.concat(" ").alias("joined_genres"),
        pl.count("genre_name").alias("genre_count")
    )
)
print(book_genre_joined.describe())
book_genre_joined.sort('genre_count', descending=True)

shape: (9, 4)
┌────────────┬───────────────┬─────────────────────────────────┬─────────────┐
│ statistic  ┆ isbn13        ┆ joined_genres                   ┆ genre_count │
│ ---        ┆ ---           ┆ ---                             ┆ ---         │
│ str        ┆ str           ┆ str                             ┆ f64         │
╞════════════╪═══════════════╪═════════════════════════════════╪═════════════╡
│ count      ┆ 197848        ┆ 197848                          ┆ 197848.0    │
│ null_count ┆ 0             ┆ 0                               ┆ 0.0         │
│ mean       ┆ null          ┆ null                            ┆ 3.448213    │
│ std        ┆ null          ┆ null                            ┆ 3.235914    │
│ min        ┆ 0-415-33024-6 ┆ -- 1872-1928 -- Juvenile liter… ┆ 1.0         │
│ 25%        ┆ null          ┆ null                            ┆ 1.0         │
│ 50%        ┆ null          ┆ null                            ┆ 2.0         │
│ 75%        ┆ null          ┆ null                            ┆ 5.0         │
│ max        ┆ 9990100000490 ┆ Философия                       ┆ 50.0        │
└────────────┴───────────────┴─────────────────────────────────┴─────────────┘

shape: (197_848, 3)
┌───────────────┬─────────────────────────────────┬─────────────┐
│ isbn13        ┆ joined_genres                   ┆ genre_count │
│ ---           ┆ ---                             ┆ ---         │
│ str           ┆ str                             ┆ u32         │
╞═══════════════╪═════════════════════════════════╪═════════════╡
│ 9780142437179 ┆ Young Adult Fiction FICTION Hi… ┆ 50          │
│ 9789022531921 ┆ Middle Earth (Imaginary place)… ┆ 46          │
│ 9780199541898 ┆ Classical fiction Resistance t… ┆ 44          │
│ 9780140862539 ┆ Comics & Graphic Novels High i… ┆ 41          │
│ 9780393926033 ┆ Young adult Classics Travel Li… ┆ 39          │
│ …             ┆ …                               ┆ …           │
│ 9781599795362 ┆ Religion                        ┆ 1           │
│ 9783764384845 ┆ Architecture                    ┆ 1           │
│ 9781591450931 ┆ Devotional calendars            ┆ 1           │
│ 9781959688235 ┆ Fantasy                         ┆ 1           │
│ 9783986771171 ┆ Classics                        ┆ 1           │
└───────────────┴─────────────────────────────────┴─────────────┘

In [99]:
book_joined = book.join(book_genre_joined, on='isbn13', how='left')
book_joined

shape: (284_893, 12)
┌───────────────┬──────────────┬──────────────┬────────────┬───┬──────────────┬───────────┬──────────────┬─────────────┐
│ isbn13        ┆ title        ┆ crawl_source ┆ isbn10     ┆ … ┆ publish_date ┆ num_pages ┆ joined_genre ┆ genre_count │
│ ---           ┆ ---          ┆ ---          ┆ ---        ┆   ┆ ---          ┆ ---       ┆ s            ┆ ---         │
│ str           ┆ str          ┆ str          ┆ str        ┆   ┆ str          ┆ i64       ┆ ---          ┆ u32         │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ str          ┆             │
╞═══════════════╪══════════════╪══════════════╪════════════╪═══╪══════════════╪═══════════╪══════════════╪═════════════╡
│ 9783946642879 ┆ Hattest du   ┆ goodreads    ┆ 394664287X ┆ … ┆ 2020-04-01   ┆ 36        ┆ LGBT Short   ┆ 9           │
│               ┆ eigentlich   ┆              ┆            ┆   ┆              ┆           ┆ Stories      ┆             │
│               ┆ schon di…    ┆              ┆            ┆   ┆              ┆           ┆ Transgender… ┆             │
│ 9782368529539 ┆ My Home Hero ┆ hardcover    ┆ 2368529535 ┆ … ┆ null         ┆ 0         ┆ Comics       ┆ 1           │
│               ┆ - tome 10    ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9780590439671 ┆ The Story Of ┆ hardcover    ┆ 0590439677 ┆ … ┆ 1993-01-01   ┆ 32        ┆ African      ┆ 5           │
│               ┆ Ruby Bridges ┆              ┆            ┆   ┆              ┆           ┆ Americans    ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Juvenile     ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Non…         ┆             │
│ 9780063216051 ┆ The Do-Over  ┆ hardcover    ┆ null       ┆ … ┆ 2023-01-01   ┆ 368       ┆ null         ┆ null        │
│ 9798329760972 ┆ Wyvern's     ┆ hardcover    ┆ 1956455752 ┆ … ┆ 2024-07-26   ┆ 572       ┆ Dystopian    ┆ 1           │
│               ┆ Gold         ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ …             ┆ …            ┆ …            ┆ …          ┆ … ┆ …            ┆ …         ┆ …            ┆ …           │
│ 9781683228615 ┆ Worry Less,  ┆ hardcover    ┆ 1683228618 ┆ … ┆ null         ┆ 0         ┆ null         ┆ null        │
│               ┆ Pray More: A ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│               ┆ Woman…       ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9781250238016 ┆ The          ┆ hardcover    ┆ 1250238013 ┆ … ┆ 1985-01-01   ┆ 432       ┆ Business &   ┆ 1           │
│               ┆ Copywriter's ┆              ┆            ┆   ┆              ┆           ┆ Economics    ┆             │
│               ┆ Handbook     ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9798322657149 ┆ The Pact     ┆ goodreads    ┆ None       ┆ … ┆ 2024-05-02   ┆ 501       ┆ Dark Reverse ┆ 3           │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Harem        ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Contemporar… ┆             │
│ 9780804747547 ┆ Yangtze      ┆ goodreads    ┆ 0804747547 ┆ … ┆ 2004-10-12   ┆ 204       ┆ null         ┆ null        │
│               ┆ Remembered:  ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│               ┆ The River …  ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9780965047623 ┆ The Very     ┆ hardcover    ┆ 0965047628 ┆ … ┆ 2000-11-24   ┆ 84        ┆ Young Adult  ┆ 2           │
│               ┆ Persistent   ┆              ┆            ┆   ┆              ┆           ┆ Fantasy      ┆             │
│               ┆ Gappers of…  ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
└───────────────┴──────────────┴──────────────┴────────────┴───┴──────────────┴───────────┴──────────────┴─────────────┘

- EDA: Quality of each source:

In [100]:
book_joined_no_null = book_joined.filter(pl.col('joined_genres').is_null() == False)
book_joined_all_nulls = book_joined.filter(pl.col('joined_genres').is_null())

In [101]:
count_with_genres = book_joined_no_null['crawl_source'].value_counts().rename({
    'count':'Has genres'
})
count_without_genres = book_joined_all_nulls['crawl_source'].value_counts().rename({
    'count':'No genres'
})
count_with_genres.join(count_without_genres, on='crawl_source')

shape: (2, 3)
┌──────────────┬────────────┬───────────┐
│ crawl_source ┆ Has genres ┆ No genres │
│ ---          ┆ ---        ┆ ---       │
│ str          ┆ u32        ┆ u32       │
╞══════════════╪════════════╪═══════════╡
│ goodreads    ┆ 43225      ┆ 28516     │
│ hardcover    ┆ 154623     ┆ 58529     │
└──────────────┴────────────┴───────────┘

In [55]:
book_joined_no_null

shape: (197_714, 12)
┌───────────────┬──────────────┬──────────────┬────────────┬───┬──────────────┬───────────┬──────────────┬─────────────┐
│ isbn13        ┆ title        ┆ crawl_source ┆ isbn10     ┆ … ┆ publish_date ┆ num_pages ┆ joined_genre ┆ genre_count │
│ ---           ┆ ---          ┆ ---          ┆ ---        ┆   ┆ ---          ┆ ---       ┆ s            ┆ ---         │
│ str           ┆ str          ┆ str          ┆ str        ┆   ┆ str          ┆ i64       ┆ ---          ┆ u32         │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ str          ┆             │
╞═══════════════╪══════════════╪══════════════╪════════════╪═══╪══════════════╪═══════════╪══════════════╪═════════════╡
│ 9781438407166 ┆ Collaborativ ┆ hardcover    ┆ 1438407165 ┆ … ┆ 1992-01-01   ┆ 172       ┆ Education    ┆ 1           │
│               ┆ e            ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│               ┆ Construction ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│               ┆ of …         ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9780751503890 ┆ The          ┆ goodreads    ┆ 0751503894 ┆ … ┆ 2001-07-01   ┆ 714       ┆ Classics     ┆ 10          │
│               ┆ Physician    ┆              ┆            ┆   ┆              ┆           ┆ Medicine     ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Adventure    ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ No…          ┆             │
│ 9783834915528 ┆ Operationali ┆ hardcover    ┆ 3834915521 ┆ … ┆ 2009-02-26   ┆ 232       ┆ Business &   ┆ 1           │
│               ┆ sierung      ┆              ┆            ┆   ┆              ┆           ┆ Economics    ┆             │
│               ┆ einer Nach…  ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9782226109552 ┆ Lorsque      ┆ hardcover    ┆ 2226109552 ┆ … ┆ 2002-01-01   ┆ 294       ┆ Fiction      ┆ 2           │
│               ┆ j'étais une  ┆              ┆            ┆   ┆              ┆           ┆ Classics     ┆             │
│               ┆ œuvre d'ar…  ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9781421590851 ┆ Neon Genesis ┆ hardcover    ┆ 1421590859 ┆ … ┆ 2016-06-14   ┆ 0         ┆ Science      ┆ 6           │
│               ┆ Evangelion   ┆              ┆            ┆   ┆              ┆           ┆ Fiction      ┆             │
│               ┆ 2-in-1…      ┆              ┆            ┆   ┆              ┆           ┆ Comics Young ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ A…           ┆             │
│ …             ┆ …            ┆ …            ┆ …          ┆ … ┆ …            ┆ …         ┆ …            ┆ …           │
│ 9780593652930 ┆ The Queen of ┆ hardcover    ┆ 0593652932 ┆ … ┆ 2022-01-01   ┆ 257       ┆ Fiction      ┆ 1           │
│               ┆ Dirt Island  ┆              ┆            ┆   ┆              ┆           ┆              ┆             │
│ 9780515158212 ┆ What Is the  ┆ hardcover    ┆ 0515158216 ┆ … ┆ 2018-01-01   ┆ 130       ┆ Juvenile     ┆ 1           │
│               ┆ World Cup?   ┆              ┆            ┆   ┆              ┆           ┆ Nonfiction   ┆             │
│ 9780316365819 ┆ The Witches: ┆ hardcover    ┆ 0316200603 ┆ … ┆ 2015-01-01   ┆ 498       ┆ History      ┆ 2           │
│               ┆ Salem, 1692  ┆              ┆            ┆   ┆              ┆           ┆ Women        ┆             │
│ 9788741859552 ┆ Det brændte  ┆ hardcover    ┆ null       ┆ … ┆ 1990-06-20   ┆ 238       ┆ Science      ┆ 5           │
│               ┆ barn         ┆              ┆            ┆   ┆              ┆           ┆ Fiction      ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Fantasy      ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Classi…      ┆             │
│ 9781508706250 ┆ The Deal     ┆ hardcover    ┆ 1508706255 ┆ … ┆ 2015-01-01   ┆ 376       ┆ College      ┆ 5           │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ students     ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Romance      ┆             │
│               ┆              ┆              ┆            ┆   ┆              ┆           ┆ Conte…       ┆             │
└───────────────┴──────────────┴──────────────┴────────────┴───┴──────────────┴───────────┴──────────────┴─────────────┘

### Data Preprocessing

In [75]:
from unidecode import unidecode

In [69]:
book_joined_preprocessed = book_joined_no_null.with_columns(
    pl.col('joined_genres')
    .map_elements(unidecode, return_dtype=pl.String)  # Apply unidecode
    .str.to_lowercase()
    .str.replace_all(r'[^a-z0-9\s-]',' ')             # Remove non-alphanumeric
    .alias('fixed_genre')
)

- Check non-alphanumeric

In [74]:
test = book_joined_preprocessed.with_columns(
    pl.col("fixed_genre").str.replace_all(r'[a-zA-Z0-9 -]', '').alias("non_alphanumeric")
)

# test.filter(pl.col('fixed_genre').str.contains('qi'))
test.filter(pl.col('non_alphanumeric') != "").select(['isbn13','fixed_genre','non_alphanumeric'])['non_alphanumeric'].value_counts()

shape: (0, 2)
┌──────────────────┬───────┐
│ non_alphanumeric ┆ count │
│ ---              ┆ ---   │
│ str              ┆ u32   │
╞══════════════════╪═══════╡
└──────────────────┴───────┘

### Model implementation

In [77]:
book_df = book_joined_preprocessed.to_pandas()

In [76]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV

In [78]:
#removing stopwords
tfidf = TfidfVectorizer(stop_words='english')

#get the tf-idf scores
#create TF-IDF matrix by fitting and transforming the data
tfidf_matrix = tfidf.fit_transform(book_df['fixed_genre'])

#shape of tfidf_matrix
tfidf_matrix.shape

(197714, 6081)

In [87]:
pd.DataFrame(tfidf_matrix[0].T.todense(), index=tfidf.get_feature_names_out(), columns=["tf-idf score"]).sort_values("tf-idf score")

             tf-idf score
000                   0.0
measurement           0.0
meadow                0.0
md                    0.0
mcnally               0.0
...                   ...
cyrano                0.0
cyprus                0.0
daisy                 0.0
zukunft               0.0
education             1.0

[6081 rows x 1 columns]

In [90]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim1 = linear_kernel(tfidf_matrix, tfidf_matrix, dense_output=False)

MemoryError: Unable to allocate 82.2 GiB for an array with shape (11037802139,) and data type int64

In [91]:
# Use your path in local
book   = pl.read_csv("./datalake/clean_merge/books.csv", schema={
    'isbn13': pl.String,
    'title': pl.String,
    'crawl_source': pl.String,
    'isbn10': pl.String,
    'description': pl.String,
    'image_url': pl.String,
    'author': pl.String,
    'language': pl.String,
    'publish_date': pl.String,
    'num_pages': pl.Int64
}, new_columns=[
    'isbn13','title','crawl_source','isbn10'
])

user   = pl.read_csv("./datalake/clean_merge/users.csv", new_columns=['full_name','account_source','userid_source_original','userid'])
rating = pl.read_csv("./datalake/clean_merge/ratings.csv", schema_overrides={
    'isbn13': pl.String,
}, new_columns=[
    'rating_score','userid','isbn13','account_source'
])

print("Book:", book)
print("User:", user)
print("Rating:", rating)

Book: shape: (284_893, 10)
┌───────────────┬────────────────┬──────────────┬────────────┬───┬───────────────┬──────────┬──────────────┬───────────┐
│ isbn13        ┆ title          ┆ crawl_source ┆ isbn10     ┆ … ┆ author        ┆ language ┆ publish_date ┆ num_pages │
│ ---           ┆ ---            ┆ ---          ┆ ---        ┆   ┆ ---           ┆ ---      ┆ ---          ┆ ---       │
│ str           ┆ str            ┆ str          ┆ str        ┆   ┆ str           ┆ str      ┆ str          ┆ i64       │
╞═══════════════╪════════════════╪══════════════╪════════════╪═══╪═══════════════╪══════════╪══════════════╪═══════════╡
│ 9783946642879 ┆ Hattest du     ┆ goodreads    ┆ 394664287X ┆ … ┆ Peer          ┆ German   ┆ 2020-04-01   ┆ 36        │
│               ┆ eigentlich     ┆              ┆            ┆   ┆ Jongeling     ┆          ┆              ┆           │
│               ┆ schon di…      ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9782368529539 ┆ My Home Hero - ┆ hardcover    ┆ 2368529535 ┆ … ┆ Masashi Asaki ┆ null     ┆ null         ┆ 0         │
│               ┆ tome 10        ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780590439671 ┆ The Story Of   ┆ hardcover    ┆ 0590439677 ┆ … ┆ Robert Coles  ┆ English  ┆ 1993-01-01   ┆ 32        │
│               ┆ Ruby Bridges   ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780063216051 ┆ The Do-Over    ┆ hardcover    ┆ null       ┆ … ┆ Suzanne Park  ┆ English  ┆ 2023-01-01   ┆ 368       │
│ 9798329760972 ┆ Wyvern's Gold  ┆ hardcover    ┆ 1956455752 ┆ … ┆ A.H. Hadley   ┆ null     ┆ 2024-07-26   ┆ 572       │
│ …             ┆ …              ┆ …            ┆ …          ┆ … ┆ …             ┆ …        ┆ …            ┆ …         │
│ 9781683228615 ┆ Worry Less,    ┆ hardcover    ┆ 1683228618 ┆ … ┆ Donna K.      ┆ null     ┆ null         ┆ 0         │
│               ┆ Pray More: A   ┆              ┆            ┆   ┆ Maltese       ┆          ┆              ┆           │
│               ┆ Woman…         ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9781250238016 ┆ The            ┆ hardcover    ┆ 1250238013 ┆ … ┆ Robert W. Bly ┆ English  ┆ 1985-01-01   ┆ 432       │
│               ┆ Copywriter's   ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│               ┆ Handbook       ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9798322657149 ┆ The Pact       ┆ goodreads    ┆ None       ┆ … ┆ Helena Sage   ┆ English  ┆ 2024-05-02   ┆ 501       │
│ 9780804747547 ┆ Yangtze        ┆ goodreads    ┆ 0804747547 ┆ … ┆ Linda Butler  ┆ English  ┆ 2004-10-12   ┆ 204       │
│               ┆ Remembered:    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│               ┆ The River …    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
│ 9780965047623 ┆ The Very       ┆ hardcover    ┆ 0965047628 ┆ … ┆ George        ┆ null     ┆ 2000-11-24   ┆ 84        │
│               ┆ Persistent     ┆              ┆            ┆   ┆ Saunders      ┆          ┆              ┆           │
│               ┆ Gappers of…    ┆              ┆            ┆   ┆               ┆          ┆              ┆           │
└───────────────┴────────────────┴──────────────┴────────────┴───┴───────────────┴──────────┴──────────────┴───────────┘
User: shape: (40_314, 4)
┌─────────────┬────────────────┬────────────────────────┬────────┐
│ full_name   ┆ account_source ┆ userid_source_original ┆ userid │
│ ---         ┆ ---            ┆ ---                    ┆ ---    │
│ str         ┆ str            ┆ i64                    ┆ i64    │
╞═════════════╪════════════════╪════════════════════════╪════════╡
│ Douglas     ┆ goodreads      ┆ 26                     ┆ 1      │
│ Courtney    ┆ goodreads      ┆ 284                    ┆ 2      │
│ kaitlin     ┆ goodreads      ┆ 675                    ┆ 3      │
│ Scott       ┆ goodreads      ┆ 713                    ┆ 4      │
│ erin        ┆ goodreads      ┆ 819                    ┆ 5      │
│ …           ┆ …              ┆ …                      ┆ …      │
│ Lily Ostler ┆ hardcover      ┆ 23475                  ┆ 40310  │
│ Keelin      ┆ hardcover      ┆ 23477                  ┆ 40311  │
│ ubyhb       ┆ hardcover      ┆ 23478                  ┆ 40312  │
│ Ainsley     ┆ hardcover      ┆ 23481                  ┆ 40313  │
│ Jose        ┆ hardcover      ┆ 23482                  ┆ 40314  │
└─────────────┴────────────────┴────────────────────────┴────────┘
Rating: shape: (1_409_156, 4)
┌──────────────┬────────┬───────────────┬────────────────┐
│ rating_score ┆ userid ┆ isbn13        ┆ account_source │
│ ---          ┆ ---    ┆ ---           ┆ ---            │
│ f64          ┆ i64    ┆ str           ┆ str            │
╞══════════════╪════════╪═══════════════╪════════════════╡
│ 3.0          ┆ 16520  ┆ 9780763625894 ┆ goodreads      │
│ 3.0          ┆ 37077  ┆ 9781504637626 ┆ hardcover      │
│ 3.0          ┆ 25783  ┆ 9780385372008 ┆ hardcover      │
│ 4.0          ┆ 26684  ┆ 9781338635201 ┆ hardcover      │
│ 4.0          ┆ 22212  ┆ 9780735219113 ┆ goodreads      │
│ …            ┆ …      ┆ …             ┆ …              │
│ 2.0          ┆ 8917   ┆ 9780609809761 ┆ goodreads      │
│ 5.0          ┆ 24565  ┆ 9782732472300 ┆ hardcover      │
│ 5.0          ┆ 25603  ┆ 9780765348272 ┆ hardcover      │
│ 4.0          ┆ 23962  ┆ 9780340163368 ┆ hardcover      │
│ 4.0          ┆ 28864  ┆ 9780425265628 ┆ hardcover      │
└──────────────┴────────┴───────────────┴────────────────┘

In [93]:
# Count based on 'crawl_source', 'account_source' in books DataFrame
count_books = book.group_by('crawl_source').agg(pl.count().alias('book_count'))
count_users = user.group_by('account_source').agg(pl.count().alias('user_count'))
count_ratings = rating.group_by('account_source').agg(pl.count().alias('rating_count'))

# Show the results
print(count_books)
print(count_users)
print(count_ratings)

shape: (2, 2)
┌──────────────┬────────────┐
│ crawl_source ┆ book_count │
│ ---          ┆ ---        │
│ str          ┆ u32        │
╞══════════════╪════════════╡
│ hardcover    ┆ 213152     │
│ goodreads    ┆ 71741      │
└──────────────┴────────────┘
shape: (2, 2)
┌────────────────┬────────────┐
│ account_source ┆ user_count │
│ ---            ┆ ---        │
│ str            ┆ u32        │
╞════════════════╪════════════╡
│ goodreads      ┆ 23569      │
│ hardcover      ┆ 16745      │
└────────────────┴────────────┘
shape: (2, 2)
┌────────────────┬──────────────┐
│ account_source ┆ rating_count │
│ ---            ┆ ---          │
│ str            ┆ u32          │
╞════════════════╪══════════════╡
│ hardcover      ┆ 963997       │
│ goodreads      ┆ 445159       │
└────────────────┴──────────────┘

C:\Users\Legion\AppData\Local\Temp\ipykernel_11888\4114412882.py:2: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  count_books = book.group_by('crawl_source').agg(pl.count().alias('book_count'))
C:\Users\Legion\AppData\Local\Temp\ipykernel_11888\4114412882.py:3: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  count_users = user.group_by('account_source').agg(pl.count().alias('user_count'))
C:\Users\Legion\AppData\Local\Temp\ipykernel_11888\4114412882.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  count_ratings = rating.group_by('account_source').agg(pl.count().alias('rating_count'))

In [ ]:
cosine_sim

In [ ]:
def recommend(title, cosine_similarity=cosine_sim):
    index = programme_list.index(title)
    sim_score = list(enumerate(cosine_sim[index]))
    sim_score = sorted(sim_score, key= lambda x: x[1], reverse=True)[1:11] #position 0 is the movie itself, thus exclude
    recommend_index = [i[0] for i in sim_score]
    rec_movie = movie['title'].iloc[recommend_index]
    rec_score = [round(i[1],4) for i in sim_score]
    rec_table = pd.DataFrame(list(zip(rec_movie,rec_score)), columns=['Recommend programme','Similarity(0-1)'])
    return rec_table

In [ ]:
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english'))  # Step 1: Apply TF-IDF
    
])

In [ ]:
# Fit and transform the data using the pipeline
grid_params = {
  'mnb__alpha': np.linspace(0.5, 1.5, 6),
  'mnb__fit_prior': [True, False],
  'tfidf_pip__tfidf_vectorizer__max_df': np.linspace(0.1, 1, 10),
  'tfidf_pip__tfidf_vectorizer__binary': [True, False],
  'tfidf_pip__tfidf_vectorizer__norm': [None, 'l1', 'l2'], 
}
clf = GridSearchCV(mnb_pipeline, grid_params)
clf.fit(train, y_train)
print("Best Score: ", clf.best_score_)
print("Best Params: ", clf.best_params_)


tfidf_pipeline.fit_transform(train)

tfidf_matrix = pipeline.fit_transform(df_pd['genre'])

# Convert the TF-IDF matrix to a DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=pipeline.named_steps['tfidf'].get_feature_names_out())

# Combine the original DataFrame with the TF-IDF values
df_pd = pd.concat([df_pd, tfidf_df], axis=1)